### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by mikevalstar** [pgilad/leasot#105]
I'd like to request a feature to ignore symlinks for the CLI version. I can ignore them by adding to the ignore portion, but if i'm using quite a few symlinks it becomes a problem. 

thanks.  Love the tool.

**Comment by pgilad** [comment]
Hmm.. what's your use case of ignoring them? What's special about them?

**Comment by mikevalstar** [comment]
so i have a project structured something like this (its more complicated in practice.. but gives you an idea):
* <main folder>\<microservice1>
* <main folder>\<microservice1>\commonlib1 -> ..\commonlib1 [symlinked]
* <main folder>\<microservice2>
* <main folder>\<microservice2>\commonlib1 -> ..\commonlib1 [symlinked]
* etc...
* <main folder>\commonlib1
* <main folder>\commonlib2

i'm running leasot in the main folder against all the sub projects at once.... so I can get a consolidated TODO list. the commonlib items get displayed multiple times due to leasot following symlinks.

**Comment by pgilad** [comment]
`leasot` uses `globby` under-the-hood, see https://github.com/pgilad/leasot/blob/master/src/cli/cli.ts#L64

Looking at `globby` which uses `fast-glob` options (https://github.com/mrmlnc/fast-glob#options-1), there are 2 that come to mind:

1. `unique` - probably won't cut it, since the file might not be considered a duplicate
2. `followSymlinkedDirectories` - might work...

Care to give it a try locally (just edit the code locally) and LMK what works best for you?

**Comment by pgilad** [comment]
Hey @mikevalstar, any updates?

**Comment by pgilad** [comment]
@mikevalstar Closing this issue for now, but feel free to re-open it in case this becomes relevant again. I'm pretty sure we can work out a solution using `followSymlinkedDirectories` option, so let me know 😄
