### ISSUE TITLE
Does not report TODOs in .vue files

### ISSUE THREAD

**Issue by tecfu** [pgilad/leasot#106]
### To Reproduce:

- Example File (example.vue)
```vue
<template>
  <div class="home-page">
    <div class="container page">
    </div>
  </div>
</template>

<script>
  // @TODO get leasot to work as advertised
  export default {
  }
</script>
```
- CLI input
```bash
$ npm i -g leasot
$ leasot example.vue
```

- CLI output 

<pre> <font color="#44AA44">✔</font> No todos/fixmes found
</pre>

**Comment by tecfu** [comment]
Instead of using leasot, one can simply do the following: 

Using **ack/ag**: 

```bash
ack -R '@todo|@fixme' src/**/*{.js,.vue}
```

Using **grep**:

```bash
grep -rni -E "@todo|@fixme" src/**/*.{js,vue}
```

These tools work as advertised and don't require a mysterious extra parameter `leasot -x` to suppress exiting with an error code.

**Comment by pgilad** [comment]
Hey @tecfu thanks for the bug report, I'll try to see why it fails to find that comment. I'm very sorry you feel this tool doesn't help you, feel free to use `pt|ag|ack|grep` or whatever tool works best for you. This is meant to easily parse various formats of comments, lowering the chances of encountering false positives in strings/variables/etc, and like any other tools, sometimes has bugs in it.

Thanks for the feedback!

**Comment by tecfu** [comment]
@pgilad Thanks for your quick and courteous response. Your tool looks great and I appreciate your effort and generosity in creating it.

**Comment by DaJoker29** [comment]
Hey, just wanted to say that I ran into this bug on my own project. However, I notice it does work if the comment is in the `<!-- -->` format. Just not the CSS (`/* */`) and JS (`//`) formats. Thought I'd mention it.

**Comment by pgilad** [comment]
Thanks @DaJoker29 will gladly accept a fix for it!

**Comment by DaJoker29** [comment]
I started combing through your code and realized it's not a bug.

We just weren't running it with the `--inline-files` flag to process inline files (since Vue components are basically three different filetypes). 

Works perfectly now!

If I can make one suggestion: you may consider making `-I` the default behavior as it seems like it would be the more prevalent use case IMO. Or possibly making a note in the README for Vue users to add the flag otherwise a good portion of their files won't parse properly.

Regardless, this is a really cool tool and I appreciate your time and effort into building and maintaining it!

**Comment by pgilad** [comment]
I think we should stay with the flag opt in, it can always be updated in the future (or possibly support config like cosmic config).

That said- if you think a readme improv would help vur users feel free to add a PR!

Thanks for the kind words
