### ISSUE TITLE
Add support for PHP # comments.

### ISSUE THREAD

**Issue by danieliser** [pgilad/leasot#55]
The following are valid in PHP
# TODO Add support for this ;)

Not sure where the best place would be. I see that PHP runs via a default config rather than its own, but this updated REGEX will work with multiple PHP scenarios.

```
var rLineComment = new RegExp('^(?:\\s*<\\?php)?\\s*(?:\\/\\/|#)' + regex + '(?:\\?>)?$', 'mig');
```

Works with

```
// TODO
# TODO
<?php // TODO ?>
<?php # TODO ?>
<div>
    <!-- As well as with indents for inline php in templates -->
    <?php # TODO Do we need this? ?>
    <div></div>
</div>
```

Looks like it may need its own config file though since those are pretty PHP specific.

Could easily be modified to check for <? php shorthand as well.

**Comment by pgilad** [comment]
PHP should definitely support `#` comments, but none of the parsers support inline or end of line comments due to the hazard of false positives:
`$var = 'This is a fake // TODO: comment'`

**Comment by danieliser** [comment]
@pgilad - Just a thought but that false positive could easily be excluded by modifying the regex to exclude matches inside quotes.

Todos will always be outside quotes so that would eliminate that issue. Can you elaborate on other potential false positives? Happy to try and address them.

**Comment by pgilad** [comment]
I wish it was that simple. Think about `var x = "this\"might'not'Be// TODO: a \"simple'string'\'\'\"\""` and the likes. And adjusting that to the way strings might be constructed in other languages...

That's why early on I went for the quick and easy way. Other examples might be multi-line comments with their nuances, Languages with multi-line statements and probably some more.

In order to be really exact, you actually need a parser for the language to detect comments, and that's a lot of maintaining and overhead that I currently do not want (not including bundling a heavy parser for each language will make this tool really heavyweight).

So yeah, beginning of line comments are great (and easy to detect). Mid line and end of line are currently a *no-go* for this project

**Comment by danieliser** [comment]
@pgilad - Though I can't imagine a string like that actually making it into code for a project I'm sure it happens, though I would bet the people that write code like that, don't use automated or CLI tools like this so you could probably be safe assuming it won't happen.

That said I do beleive PHP needs its own ruleset here as there are a few that should be available without issue.

For instance inlining a php comment above html in a template. The todo is a single line comment with opening and closing PHP tags.

    <?php // TODO some thing or another ?>

That is simple enough and the only thing your looking for at the end is possibly ?> so you can still safely pretend its not doing any end of line detection.

I think it should be safe enough, but understand the hesitancy. One of my WP plugins has 60k active sites, makes major change sets tough to ensure complete backward compatibility.

**Comment by pgilad** [comment]
Currently decided to close this. I don't have plans to support inline or end of line comments in the future. It adds too much complexity and this project is meant to stay a simple cross-language tool for extracting and reporting todos/fixmes.

Thanks for the suggestion though!
