### ISSUE TITLE
Multi-line todo with twig parser does not work

### ISSUE THREAD

**Issue by SuyogSoti** [pgilad/leasot#71]
Hi,
I love leasot, and thank you so much for working on it. I have however noticed that multi-line comments do now work with the twig parser. For example
```
<!--
TODO: this is a 
longer TODO description
-->
```
will not show any todo outputs. That means that todo in block comments in markdown, html and all of its derivations will not work.

**Comment by pgilad** [comment]
I don't think there was an intention of providing multi-line comments support, especially since some people might actually just want a single line TODO description.

To keep this tool simple I don't want to add complicated scenarios to the parsing. That said - if you want to write your own parser and use it - feel free to add a PR and provide an alternate parser
